# Amsterdan

Combinatorics implemented with `numpy` and `scipy`.

In [1]:
import numpy as np
import scipy as sc

## Cartesian Product

https://en.wikipedia.org/wiki/Cartesian_product

In mathematics, specifically set theory, the Cartesian product of two sets A and B, denoted A × B, is the set of all ordered pairs (a, b) where a is in A and b is in B.

$$ \mathbf{A} X \mathbf{B} = \{ (\boldsymbol{\alpha}, \boldsymbol{\beta}) | \boldsymbol{\alpha} \in \mathbf{A}, \boldsymbol{\beta} \in \mathbf{B} \} $$

$$ |\mathbf{A} X \mathbf{B}| = |\mathbf{A}| X |\mathbf{B}| $$

In [386]:
def cartesian(*arrays) -> np.matrix:
    """
    Generate a cartesian product of input arrays.
    """
    if len(arrays) == 1:
        return arrays[0]
    dtype: np.dtype = arrays[0][0].dtype
    X: np.ndarray = arrays[0]
    Y: np.ndarray = cartesian(*arrays[1:])
    X = X.reshape(X.shape[0], X.shape[1] if X.ndim > 1 else 1)
    Y = Y.reshape(Y.shape[0], Y.shape[1] if Y.ndim > 1 else 1)
    n: int = Y.shape[0] * X.shape[0]
    X = np.repeat(X, Y.shape[0], axis=0)
    Y = np.tile(Y, (int(n / Y.shape[0]), 1))
    return np.insert(Y, 0, X.T[0], axis=1)

In [387]:
X: np.matrix = np.array([ 0, 1 ])
Y: np.matrix = np.array([ 2, 3 ])
Z: np.matrix = np.array([ 4, 5 ])
print(cartesian(X, Y, Z))

[[0 2 4]
 [0 2 5]
 [0 3 4]
 [0 3 5]
 [1 2 4]
 [1 2 5]
 [1 3 4]
 [1 3 5]]


In [388]:
X: np.ndarray = np.arange(2)
Y: np.ndarray = np.arange(3)
print(cartesian(X, Y))

[[0 0]
 [0 1]
 [0 2]
 [1 0]
 [1 1]
 [1 2]]


In [389]:
X: np.matrix = np.matrix([ [0], [1] ])
Y: np.matrix = np.matrix([ [3,3], [4, 4] ])
print(cartesian(X, Y))

[[0 3 3]
 [0 4 4]
 [1 3 3]
 [1 4 4]]


## Permutations

https://www.ck12.org/probability/permutations-with-repetition/lesson/Permutations-with-Repetition-BSC-PST/

https://brilliant.org/wiki/permutations-with-repetition/

A permutation of a set of objects is an ordering of those objects. When some of those objects are identical, the situation is transformed into a problem about permutations with repetition.

$$ \mathbf{A}X\mathbf{A} = \{ (\boldsymbol{\alpha}_i, \boldsymbol{\alpha}_j) | \boldsymbol{\alpha}_i \in \mathbf{A}, \boldsymbol{\alpha}_j \in \mathbf{A} \} $$

$$ |\mathbf{A} X \mathbf{A}| = |\mathbf{A}|^n $$

How many different ways can the letters P, Q, R, S be arranged?

In [398]:
X: np.matrix = np.array([ 1, 2, 3, 4 ])
print(cartesian(X, X, X, X).shape[0])

256


How many different ways can the letters P, Q, R, S be arranged in buckets of 3 letters?

In [399]:
X: np.matrix = np.array([ 1, 2, 3, 4 ])
print(cartesian(X, X, X).shape[0])

64


How many different ways can the letters A, A, A, B, C be arranged

In [406]:
X: np.matrix = np.array([ 1, 1, 1, 2, 3 ])
X: np.matrix = np.array([ 1, 1, 1, 2, 3 ])
print(cartesian(X, X, X, X).shape[0])

625
